### PR TITLE
docs(README): mention tagged releases instead of cloning repo

### PR DESCRIPTION
**Pull request by BlankParticle**

### CODE REVIEW

**Review by sgoudham — CHANGES_REQUESTED** [review]
Hey there :wave: 

To summarise what we talked about on discord, we appreciate your efforts in wanting to contribute to this repository but we'd like to avoid install bash scripts!

I think it would be nicer to make use of GitHub releases as the benefits are two-fold:

1. We can start to version this theme and give users a better indication on what it means to update the theme files for btop
2. By adding the `themes/` directory as an asset in the GitHub releases, we can make use of common utilities such as `curl` and `tar` to automatically install the theme via the terminal.

I've tagged and released https://github.com/catppuccin/btop/releases/tag/1.0.0 and uploaded the themes as a `.tar.gz`. I was able to install the theme automatically by running the following command:
```shell
curl -L https://github.com/catppuccin/btop/releases/download/1.0.0/themes.tar.gz | tar -xvz --directory="$HOME/.config/btop/themes" --strip-components=1 --wildcards "themes/*"
```

I wanted to use `$XDG_CONFIG_HOME` but I actually don't seem to have that set and the syntax for the fish shell is not the same as zsh so we might want 2 different variations compatible for (bash/zsh) and fish.

What do you think?

**Comment by BlankParticle** [comment]
For `zsh` I would like to slightly modify the script to respect `$XDG_CONFIG_HOME`, so the command might look like this.
```bash
curl -L https://github.com/catppuccin/btop/releases/download/1.0.0/themes.tar.gz | tar -xvz --directory="${XDG_CONFIG_HOME:-$HOME/.config}/btop/themes" --strip-components=1 --wildcards "themes/*"
```
This looks for `XDG_CONFIG_HOME` if set otherwise fallbacks to `$HOME/.config`, but for `fish` shell there is no fallback syntax (`${this:-"that"}`) I [belive](https://stackoverflow.com/questions/54545610/whats-the-equivalent-to-var-defaultvalue-in-fish).

What do you want to do for `fish`?
We can write a verbose script for `fish`, but that would be same as what I have done for `bash`

Otherwise I will remove the install script and change the instructions in README

**Review by sgoudham — CHANGES_REQUESTED** [review]
Hey there, just revisiting this again with a fresh perspective.

I'm not actually sure if we need to include a fancy curl/tar command for the person to use. If we don't go through the effort of providing multiple compatible commands for (bash/zsh), fish, nushell, etc. - people might just raise issues about that instead.

@backwardspy and I discussed this more and we think that changing the following is good enough. The baseline of downloading from a release is nicer than cloning the repository and people can choose whatever suits them best to do this:
```diff
- 1. Clone this repository locally
+ 1. Download the [latest release](https://github.com/catppuccin/btop/releases/latest)
```

Once the install script has been removed and the README updated to mention downloading from the latest release instead of cloning the repository, I think we'll be good to merge this :+1: (the bpytop changes are fine)

**Comment by BlankParticle** [comment]
After some thoughts, I also believe its best to avoid bash scripts or install commands for installing just a simple theme, but I am happy that my effort made the theme into versioned releases instead of cloning the repo to install the theme.
I have updated the README with updated instructions.

**Review by sgoudham — APPROVED** [review]
Looks good to me, thank you!

**Pull request merged**
